name: minesweeper
description: A Minesweeper game built with Flutter Flame

version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flame: ^1.27.0
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/sounds/