name: minesweeper
description: A Minesweeper game built with Flutter Flame

version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flame_audio: ^1.0.0
  shared_preferences: ^2.5.3
  flame: ^1.27.0
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/images/explosion.png
    - assets/audio/explosion.mp3
    - assets/audio/flag.mp3