name: minesweeper
description: A Minesweeper game built with Flutter Flame

version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  audioplayers: ^6.4.0
  flame_audio: ^2.11.5
  http: ^1.3.0
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  flame: ^1.27.0
  flutter:
    sdk: flutter

flutter:
  assets:
    - assets/images/explosion.png
    - assets/audio/explosion.mp3
    - assets/audio/flag.mp3